project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Rachel Garton" 
    right: 
      - icon: github
        href: https://github.com/rachelgarton
  title: "Rachel's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - SMPA_3333_Paper_Example.qmd
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



