---
title: "Advanced News Writing Story Example"
author: "Rachel Garton"
---

**All Things Go Creator Summit Draws Attention to an Evolving Industry**

**WASHINGTON** --- Developers of the annual All Things Go Music Festival highlighted the importance of women in media in light of a changing industry on Oct. 15 during the festival's Creator Summit at the Eaton Hotel in Washington.

Through discussion tables and a series of speakers divided by profession, the creator summit used keynote speakers to focus upon how women fit into the music industry and offered encouragement for attendees looking to get into media.

"One of the reasons we love this festival --- All Things Go --- is because it's very female driven. I never realized that it's just a big support for female artists and I think it's important to see women headliners in big festivals," said Wendi "Madison" Rickman, a SiriusXM host and creator summit leader.

The All Things Go Festival, also known as the All Things Go Fall Classic, was co-founded in 2011 by Adrian Maseda, Will Suter, Zack Friendly and Stephen Vallimarescu. The festival features mainly alternative and indie-based female artists, but is also known for its support of LGBTQ+ artists.

The concert series has grown so much in popularity that developers have been forced to quadruple the venue capacity. Just this year, creators announced that the festival would be making the move from Union Market --- where the festival was founded --- to Merriweather Post Pavilion in Columbia, Md., which has a capacity of over 19,000 people.

While prominent artists such as MUNA, Melanie Martinez and Billie Eilish have all headlined the festival in recent years, the support towards female artists goes on behind the scenes as well.

"A lot of my spare time is, you know, trying to build a network of superstars in this industry of not only women but men as well ... everybody needs a helping hand to kind of guide them and say that you can make it," said President and Managing Partner Jeanine McLean of MBK Entertainment.

McLean, who played a prominent role in rolling out this year's festival, has also represented artists such as H.E.R. and Alicia Keys. In her year off from helping produce the All Things Go Festival, McLean aided in creating an online series with H.E.R. titled "Girls With Guitars," which spotlights female guitar players to give them a platform to talk about their love of music.

Vice President of A&R Admin Nikisha Bailey said that "Girls With Guitars" is one example of how drastically the industry has changed since the beginning of the COVID-19 pandemic.

"We have artists that record a song in their hotel and they want it up the next day. So just even in terms of how you pivot to a company with those artists and how quick they want to release music, like to have people finding sounds from TikTok ... I'm not even sure where it's going to go. Like, where do you go after this?" Bailey said.

TikTok, a social media app that allows creators to post videos --- both for fun and promotional purposes --- has revolutionized the music industry. A study by MRC data demonstrated how trending songs on the app commonly end up on the Billboard and Spotify charts, as users have the tendency to seek out trending "sounds" on music-streaming sites.

"Social media is interfering with our actual career. You know it's, like, almost as important as making images and so is making a TikTok, and I am horrible. I was joking the other day because I was trying to make a 15 second TikTok within five hours," said Chelsea Lee of the band SHAED.

SHAED, who have broken genre barriers with their multi-platinum song "Trampoline," has recently made the transition into a mostly virtual career following the announcement of Lee's pregnancy. Although the trio will eventually return to in-person events, they currently plan on staying virtual for the foreseeable future.

"I mean, we became like expert couch concert consumers ... and silver lining wise, we finally got a chance to kind of rest and write an album. Nothing beats the in-person stuff, but it was a (nice) alternative for us," said Lee.

SHAED is not the only artist to make a transition into more experimental ways of promoting their music. Within the past year, multiple artists have made the switch into virtual concert platforms such as Roblox, Instagram Live or Veeps. Although non-traditional, the appearances appear to be successful, with Lil Nas X's Roblox concert gaining 33 million views, and band Twenty One Pilots kicking off their first tour in two years with a virtual Roblox concert experience.

"You do have to be in so many places at once. As a musician, it's been wild to see the innovation that's happened, even just during this period of time of COVID. People, you know, we're kind of forced to really revolutionize the way that they were thinking about virtual and the gaming industry," said key-speaker Jennifer Leiweke.

While the music industry has always been fast paced, social media is changing the game once more, with women spear-heading the competition.
